version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: my_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: 01_fund_reconciliation
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Optionally mount schema/data files
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  postgres_data:
